---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - gravityclusters
  - gravitymachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - gravityclusters/finalizers
  - gravitymachines/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - gravityclusters/status
  - gravitymachines/status
  verbs:
  - get
  - patch
  - update
